### PR TITLE
fixed internal url detection

### PR DESCRIPTION
**Pull request by cnlpete**
The link detection was not working for me since they changed the internal urls.
Also search was not working

### CODE REVIEW

**Comment by black-sheep-dev** [comment]
Thanks for the pull request. But what are the differences between api2 and api2u?
The response seems to be the same?!?

**Comment by cnlpete** [comment]
Humm, i don't really know, i always get redirected to api2u...

maybe we can split this and only do the "relaxed" url check...

**Comment by cnlpete** [comment]
Ok, i removed the api endpoint changes and only committed the relaxed internal url detection

**Comment by black-sheep-dev** [comment]
Thanks will merge this. Seems that some internal links are pointing to api2u. Let's see what will be changed in the future.

**Pull request merged**
